### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by ambidot**
Hi! I've been debugging and made some improvements. Please take a look. There are still numerous issues, but many workshop scenes have gone from malfunctioning to a semi-working state.

image
image
image
image

### CODE REVIEW

**Comment by Almamu** [comment]
Can one of the admins verify this patch?

**Comment by ambidot** [comment]
Alexis, have you talked to the wallpaper devs (Kristjan and David) about opening up some of the technical details of Wallpaper Engine? I'm looking into implementing support for pixel art animations such as [this one](https://steamcommunity.com/sharedfiles/filedetails/?id=2169529482) but having trouble finding data in its TEX file on how the frames are arranged. Currently they're drawn as the entire ARGB8 across the screen.

sdfjkl

**Comment by ambidot** [comment]
Specifically, this is the scene.json for that scene. I'm not sure if there's a good way to deduce the layout of the frames other than assuming they go left-to-right, top-to-bottom, and fill up the margin.

```
{
    "camera": {
        "center": "0.000 0.000 -1.000",
        "eye": "0.000 0.000 0.000",
        "up": "0.000 1.000 0.000"
    },
    "general": {
        "ambientcolor": "0.300 0.300 0.300",
        "bloom": false,
        "bloomstrength": 2.0,
        "bloomthreshold": 0.6499999761581421,
        "camerafade": true,
        "cameraparallax": false,
        "cameraparallaxamount": 0.5,
        "cameraparallaxdelay": 0.10000000149011612,
        "cameraparallaxmouseinfluence": 0.0,
        "camerapreview": true,
        "camerashake": false,
        "camerashakeamplitude": 0.5,
        "camerashakeroughness": 0.0,
        "camerashakespeed": 1.100000023841858,
        "clearcolor": "0.137 0.545 0.514",
        "clearenabled": true,
        "farz": 10000.0,
        "fov": 50.0,
        "nearz": 0.009999999776482582,
        "orthogonalprojection": {
            "height": 576,
            "width": 1024
        },
        "skylightcolor": "0.300 0.300 0.300"
    },
    "objects": [
        {
            "alignment": "center",
            "alpha": 1.0,
            "angles": "0.000 0.000 0.000",
            "color": "1.000 1.000 1.000",
            "colorBlendMode": 0,
            "copybackground": true,
            "id": 13,
            "image": "models/821e3ff5d27bd8eb0c99a580386d29b3.json",
            "ledsource": false,
            "locktransforms": true,
            "name": "821e3ff5d27bd8eb0c99a580386d29b3",
            "origin": "512.000 288.000 0.000",
            "parallaxDepth": "1.000 1.000",
            "perspective": false,
            "scale": "1.000 1.000 1.000",
            "size": "1024.000 576.000",
            "solid": true,
            "visible": true
        }
    ]
}
```

**Comment by Almamu** [comment]
Before anything else, thanks for the contributions. I'll take a look at them today, merge the changes (I'm not in front of my computer right now, for now I'll Trigger build on my Jenkins instance so I have a binary to test when I'm at home) and port them to data-separation when they apply (as that branch should handle more of the wp-engine's features like render targets/complex materials once It's done).

> Hi! I've been debugging and made some improvements. Please take a look. There are still numerous issues, but many workshop scenes have gone from malfunctioning to a semi-working state.

Anything that improves the current support and quality is welcome'd ;)

> Alexis, have you spoken to the WE devs Kristjan or David or Tim about opening up some of the technical details of Wallpaper Engine?

Not at all, this started like a small RE attempt and to teach me some 3D stuff (as It's evident even math is not my strong point). I didn't expect to get more than a couple of backgrounds running to be honest. It's something that would be cool to do If I had as much time as I'd like to dedicate to the project.

**Comment by ambidot** [comment]
I'm a little confused on the data-separation branch. Is it intended to replace `master`? Should I be working on data-separation rather than master?

I tried cloning it and debugging with Visual Studio but it segfaults on `CPkgReader::scanPkgHeader ()` on the line `this->m_context->getDevice ()->getLogger ()->log ("unexpected package header", this->m_file->getFileName ().c_str (), irr::ELL_ERROR);`. Specifically, `getDevice ()` returns 0x6E6F and segfaults when attempting to call any of its member functions with `->`.

**Comment by Almamu** [comment]
Yes, It is intended to replace master in the long run. As it is right now, most of the data-separation branch is just experimental code tho, so It might get in the way of getting things right on things like formats, textures, etc... In the meantime I'll port the changes to the new data-separation branch manually until It's ready to replace master. There's only one thing that is on data-separation that isn't on master, and that is video backgrounds support.

I guess the issue is with the error reporting and the initialization of the context. I'll fix the error so It stops happening.

**Pull request merged**
